name: CI
on: [ push, pull_request ]
jobs:
  build-and-test:
    name: 构建和测试
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 24 ]
    runs-on: ${{ matrix.os }}
    steps:

      - name: 签出代码
        uses: actions/checkout@v5

      - name: 启动默认的 MySQL
        if: ${{ runner.os == 'Linux' }}
        run: sudo systemctl start mysql.service

      - name: 安装 JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: 使用 Maven 进行构建和测试
        run: mvn package --batch-mode

      - name: 上传 构建和测试 生成的文件
        uses: actions/upload-artifact@v4
        with:
          name: live-room-watcher-artifact-${{ runner.os }}-${{ matrix.java }}
          path: target/
